### ISSUE TITLE
Minstall error

### ISSUE THREAD

**Issue by DavidMcKenna** [komh/ksoftseq#5]
When I try to minstall ksoftseq, I get an error:

[C:\junk\dl\ksoftseq]minstall.exe
MINSTALL - Multimedia Installer (CLI/CID) - by Kiewitz
[C:\junk\dl\ksoftseq\control.scr] Unlisted script 'ksoftseq.scr'
Return-Code 8 (CID: Success, error(s) logged)

 Any hints?

**Comment by komh** [comment]
I've confirmed. Try this, [minstall_fix.zip](https://github.com/komh/ksoftseq/files/5166862/minstall_fix.zip)

Unzip and copy them into the directory where installation files are.

Your MINSTALL is different from mine, which is MINSTALL IBM 14.057.

**Comment by DavidMcKenna** [comment]
Thanks - that works. I have installed and am able to play MIDI files by double-clicking them! First time I could do that since Warp3 days. Can you recommend a soundfont file to use (I got one called 'merlin_gmv32.sf2)? Might be good to list a soundfont file in the README too. Thanks for creating this software!

**Comment by komh** [comment]
Good! 

Sorry I don't know which soundfont is best. And for a list, I'll think more about that, but not positive.

Thanks!
