### ISSUE TITLE
Some MIDI files hang desktop

### ISSUE THREAD

**Issue by DavidMcKenna** [komh/ksoftseq#6]
I've been enjoying playing MIDI files using ksoftseq and for the most part it works well, but occasionally I come across a file that will not play. The icon cross-hatches and says 'Starting file...', a CPU goes to 100% and eventually the desktop hangs requiring a CAD. The same file plays fine with Alex Taylor's Timidity player. I will attach an example file (rename it solace.mid - Github doesn't allow *.mid files).

**Comment by DavidMcKenna** [comment]
Had to use a different browser to upload..
[Uploading solace.txt…]()

**Comment by komh** [comment]
I'm afraid that I cannot download it. Please re-upload. And how about using zip ?

**Comment by DavidMcKenna** [comment]
Sorry, let's try again with a zip...
[solace.zip](https://github.com/komh/ksoftseq/files/5187800/solace.zip)

**Comment by komh** [comment]
I've confirmed that kmididec has a problem with your solace.mid. I'll try to fix this, soon. 

Thanks!

**Comment by komh** [comment]
Here the test version.

[ksoftseq_test.zip](https://github.com/komh/ksoftseq/files/5194912/ksoftseq_test.zip)

To install,

1. Unlock x:\mmos2\dll\ksoftseq.dll
2. Copy unzipped ksoftseq.dll into x:\mmos2\dll

Where x: is your boot drive.

Good luck!

**Comment by DavidMcKenna** [comment]
Thanks! Every MIDI file I have will play now
