### ISSUE TITLE
Some MIDI files never stop playing

### ISSUE THREAD

**Issue by DavidMcKenna** [komh/ksoftseq#7]
This is related to issue #6.

 Some MIDI files play (when double-clicking a file), but when the music is over, the file keeps 'playing' by showing the count down of time and does not stop until double-clicked again. The same files I have as described in issue 6 do this, so you should be able to see it with the 'solace.mid' file I uploaded earlier (after about 5 minutes). Most other files stop when the music is finished.

**Comment by komh** [comment]
I already know that. But it's not a problem of ksoftseq. Just its real playing time is more long, about 7:52. You can confirm other midi players.
